/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cosmic-speedways-6fcaba8fa99842679075e8b16e8963cc
Title: Cosmic Speedways
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Background(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./assets/models/cosmic_speedways.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Animation"].play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.125}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Torus_1" position={[4.8, 0, 0]}>
                <mesh
                  name="Object_4"
                  
                  
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder_0"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_6"
                    
                    
                    geometry={nodes.Object_6.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus001_3" position={[-4.8, 0, 0]}>
                <mesh
                  name="Object_8"
                  
                  
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder001_2"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_10"
                    
                    
                    geometry={nodes.Object_10.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus002_5" position={[0, 0, -4.8]}>
                <mesh
                  name="Object_12"
                  
                  
                  geometry={nodes.Object_12.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder002_4"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_14"
                    
                    
                    geometry={nodes.Object_14.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus003_7" position={[0, 0, 4.8]}>
                <mesh
                  name="Object_16"
                  
                  
                  geometry={nodes.Object_16.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder003_6"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_18"
                    
                    
                    geometry={nodes.Object_18.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus004_9" position={[3.394, 0, 3.394]}>
                <mesh
                  name="Object_20"
                  
                  
                  geometry={nodes.Object_20.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder004_8"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_22"
                    
                    
                    geometry={nodes.Object_22.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus005_11" position={[-3.394, 0, -3.394]}>
                <mesh
                  name="Object_24"
                  
                  
                  geometry={nodes.Object_24.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder005_10"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_26"
                    
                    
                    geometry={nodes.Object_26.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus006_13" position={[3.394, 0, -3.394]}>
                <mesh
                  name="Object_28"
                  
                  
                  geometry={nodes.Object_28.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder006_12"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_30"
                    
                    
                    geometry={nodes.Object_30.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus007_15" position={[-3.394, 0, 3.394]}>
                <mesh
                  name="Object_32"
                  
                  
                  geometry={nodes.Object_32.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder007_14"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_34"
                    
                    
                    geometry={nodes.Object_34.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus008_17" position={[4.454, 0, 1.788]}>
                <mesh
                  name="Object_36"
                  
                  
                  geometry={nodes.Object_36.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder008_16"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_38"
                    
                    
                    geometry={nodes.Object_38.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus009_19" position={[-4.454, 0, -1.788]}>
                <mesh
                  name="Object_40"
                  
                  
                  geometry={nodes.Object_40.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder009_18"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_42"
                    
                    
                    geometry={nodes.Object_42.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus010_21" position={[1.788, 0, -4.454]}>
                <mesh
                  name="Object_44"
                  
                  
                  geometry={nodes.Object_44.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder010_20"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_46"
                    
                    
                    geometry={nodes.Object_46.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus011_23" position={[-1.788, 0, 4.454]}>
                <mesh
                  name="Object_48"
                  
                  
                  geometry={nodes.Object_48.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder011_22"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_50"
                    
                    
                    geometry={nodes.Object_50.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus012_25" position={[1.885, 0, 4.414]}>
                <mesh
                  name="Object_52"
                  
                  
                  geometry={nodes.Object_52.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder012_24"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_54"
                    
                    
                    geometry={nodes.Object_54.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus013_27" position={[-1.885, 0, -4.414]}>
                <mesh
                  name="Object_56"
                  
                  
                  geometry={nodes.Object_56.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder013_26"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_58"
                    
                    
                    geometry={nodes.Object_58.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus014_29" position={[4.414, 0, -1.885]}>
                <mesh
                  name="Object_60"
                  
                  
                  geometry={nodes.Object_60.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder014_28"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_62"
                    
                    
                    geometry={nodes.Object_62.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus015_31" position={[-4.414, 0, 1.885]}>
                <mesh
                  name="Object_64"
                  
                  
                  geometry={nodes.Object_64.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder015_30"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_66"
                    
                    
                    geometry={nodes.Object_66.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus016_33" position={[4.697, 0, 0.988]}>
                <mesh
                  name="Object_68"
                  
                  
                  geometry={nodes.Object_68.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder016_32"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_70"
                    
                    
                    geometry={nodes.Object_70.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus017_35" position={[-4.697, 0, -0.988]}>
                <mesh
                  name="Object_72"
                  
                  
                  geometry={nodes.Object_72.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder017_34"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_74"
                    
                    
                    geometry={nodes.Object_74.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus018_37" position={[0.988, 0, -4.697]}>
                <mesh
                  name="Object_76"
                  
                  
                  geometry={nodes.Object_76.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder018_36"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_78"
                    
                    
                    geometry={nodes.Object_78.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus019_39" position={[-0.988, 0, 4.697]}>
                <mesh
                  name="Object_80"
                  
                  
                  geometry={nodes.Object_80.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder019_38"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_82"
                    
                    
                    geometry={nodes.Object_82.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus020_41" position={[2.623, 0, 4.02]}>
                <mesh
                  name="Object_84"
                  
                  
                  geometry={nodes.Object_84.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder020_40"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_86"
                    
                    
                    geometry={nodes.Object_86.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus021_43" position={[-2.623, 0, -4.02]}>
                <mesh
                  name="Object_88"
                  
                  
                  geometry={nodes.Object_88.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder021_42"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_90"
                    
                    
                    geometry={nodes.Object_90.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus022_45" position={[4.02, 0, -2.623]}>
                <mesh
                  name="Object_92"
                  
                  
                  geometry={nodes.Object_92.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder022_44"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_94"
                    
                    
                    geometry={nodes.Object_94.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus023_47" position={[-4.02, 0, 2.623]}>
                <mesh
                  name="Object_96"
                  
                  
                  geometry={nodes.Object_96.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder023_46"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_98"
                    
                    
                    geometry={nodes.Object_98.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus024_49" position={[3.991, 0, 2.667]}>
                <mesh
                  name="Object_100"
                  
                  
                  geometry={nodes.Object_100.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder024_48"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_102"
                    
                    
                    geometry={nodes.Object_102.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus025_51" position={[-3.991, 0, -2.667]}>
                <mesh
                  name="Object_104"
                  
                  
                  geometry={nodes.Object_104.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder025_50"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_106"
                    
                    
                    geometry={nodes.Object_106.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus026_53" position={[2.667, 0, -3.991]}>
                <mesh
                  name="Object_108"
                  
                  
                  geometry={nodes.Object_108.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder026_52"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_110"
                    
                    
                    geometry={nodes.Object_110.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus027_55" position={[-2.667, 0, 3.991]}>
                <mesh
                  name="Object_112"
                  
                  
                  geometry={nodes.Object_112.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder027_54"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_114"
                    
                    
                    geometry={nodes.Object_114.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus028_57" position={[0.936, 0, 4.708]}>
                <mesh
                  name="Object_116"
                  
                  
                  geometry={nodes.Object_116.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder028_56"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_118"
                    
                    
                    geometry={nodes.Object_118.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus029_59" position={[-0.936, 0, -4.708]}>
                <mesh
                  name="Object_120"
                  
                  
                  geometry={nodes.Object_120.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder029_58"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_122"
                    
                    
                    geometry={nodes.Object_122.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus030_61" position={[4.708, 0, -0.936]}>
                <mesh
                  name="Object_124"
                  
                  
                  geometry={nodes.Object_124.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder030_60"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_126"
                    
                    
                    geometry={nodes.Object_126.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus031_63" position={[-4.708, 0, 0.936]}>
                <mesh
                  name="Object_128"
                  
                  
                  geometry={nodes.Object_128.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder031_62"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_130"
                    
                    
                    geometry={nodes.Object_130.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus032_65" position={[4.781, -0.433, -0.005]}>
                <mesh
                  name="Object_132"
                  
                  
                  geometry={nodes.Object_132.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder032_64"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_134"
                    
                    
                    geometry={nodes.Object_134.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus033_67" position={[-4.781, 0.423, -0.005]}>
                <mesh
                  name="Object_136"
                  
                  
                  geometry={nodes.Object_136.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder033_66"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_138"
                    
                    
                    geometry={nodes.Object_138.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus034_69" position={[-0.428, -4.786, -0.005]}>
                <mesh
                  name="Object_140"
                  
                  
                  geometry={nodes.Object_140.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder034_68"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_142"
                    
                    
                    geometry={nodes.Object_142.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus035_71" position={[0.428, 4.776, -0.005]}>
                <mesh
                  name="Object_144"
                  
                  
                  geometry={nodes.Object_144.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder035_70"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_146"
                    
                    
                    geometry={nodes.Object_146.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus036_73" position={[3.683, 3.073, -0.005]}>
                <mesh
                  name="Object_148"
                  
                  
                  geometry={nodes.Object_148.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder036_72"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_150"
                    
                    
                    geometry={nodes.Object_150.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus037_75" position={[-3.683, -3.083, -0.005]}>
                <mesh
                  name="Object_152"
                  
                  
                  geometry={nodes.Object_152.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder037_74"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_154"
                    
                    
                    geometry={nodes.Object_154.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus038_77" position={[3.078, -3.688, -0.005]}>
                <mesh
                  name="Object_156"
                  
                  
                  geometry={nodes.Object_156.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder038_76"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_158"
                    
                    
                    geometry={nodes.Object_158.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus039_79" position={[-3.078, 3.678, -0.005]}>
                <mesh
                  name="Object_160"
                  
                  
                  geometry={nodes.Object_160.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder039_78"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_162"
                    
                    
                    geometry={nodes.Object_162.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus040_81" position={[4.596, 1.379, -0.005]}>
                <mesh
                  name="Object_164"
                  
                  
                  geometry={nodes.Object_164.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder040_80"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_166"
                    
                    
                    geometry={nodes.Object_166.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus041_83" position={[-4.596, -1.389, -0.005]}>
                <mesh
                  name="Object_168"
                  
                  
                  geometry={nodes.Object_168.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder041_82"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_170"
                    
                    
                    geometry={nodes.Object_170.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus042_85" position={[1.384, -4.601, -0.005]}>
                <mesh
                  name="Object_172"
                  
                  
                  geometry={nodes.Object_172.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder042_84"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_174"
                    
                    
                    geometry={nodes.Object_174.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus043_87" position={[-1.384, 4.591, -0.005]}>
                <mesh
                  name="Object_176"
                  
                  
                  geometry={nodes.Object_176.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder043_86"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_178"
                    
                    
                    geometry={nodes.Object_178.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus044_89" position={[2.271, 4.224, -0.005]}>
                <mesh
                  name="Object_180"
                  
                  
                  geometry={nodes.Object_180.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder044_88"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_182"
                    
                    
                    geometry={nodes.Object_182.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus045_91" position={[-2.271, -4.234, -0.005]}>
                <mesh
                  name="Object_184"
                  
                  
                  geometry={nodes.Object_184.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder045_90"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_186"
                    
                    
                    geometry={nodes.Object_186.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus046_93" position={[4.229, -2.276, -0.005]}>
                <mesh
                  name="Object_188"
                  
                  
                  geometry={nodes.Object_188.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder046_92"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_190"
                    
                    
                    geometry={nodes.Object_190.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus047_95" position={[-4.229, 2.266, -0.005]}>
                <mesh
                  name="Object_192"
                  
                  
                  geometry={nodes.Object_192.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder047_94"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_194"
                    
                    
                    geometry={nodes.Object_194.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus048_97" position={[4.767, 0.561, -0.005]}>
                <mesh
                  name="Object_196"
                  
                  
                  geometry={nodes.Object_196.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder048_96"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_198"
                    
                    
                    geometry={nodes.Object_198.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus049_99" position={[-4.767, -0.571, -0.005]}>
                <mesh
                  name="Object_200"
                  
                  
                  geometry={nodes.Object_200.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder049_98"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_202"
                    
                    
                    geometry={nodes.Object_202.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus050_101" position={[0.566, -4.772, -0.005]}>
                <mesh
                  name="Object_204"
                  
                  
                  geometry={nodes.Object_204.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder050_100"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_206"
                    
                    
                    geometry={nodes.Object_206.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus051_103" position={[-0.566, 4.762, -0.005]}>
                <mesh
                  name="Object_208"
                  
                  
                  geometry={nodes.Object_208.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder051_102"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_210"
                    
                    
                    geometry={nodes.Object_210.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus052_105" position={[2.97, 3.765, -0.005]}>
                <mesh
                  name="Object_212"
                  
                  
                  geometry={nodes.Object_212.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder052_104"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_214"
                    
                    
                    geometry={nodes.Object_214.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus053_107" position={[-2.97, -3.775, -0.005]}>
                <mesh
                  name="Object_216"
                  
                  
                  geometry={nodes.Object_216.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder053_106"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_218"
                    
                    
                    geometry={nodes.Object_218.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus054_109" position={[3.77, -2.975, -0.005]}>
                <mesh
                  name="Object_220"
                  
                  
                  geometry={nodes.Object_220.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder054_108"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_222"
                    
                    
                    geometry={nodes.Object_222.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus055_111" position={[-3.77, 2.966, -0.005]}>
                <mesh
                  name="Object_224"
                  
                  
                  geometry={nodes.Object_224.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder055_110"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_226"
                    
                    
                    geometry={nodes.Object_226.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus056_113" position={[4.213, 2.296, -0.005]}>
                <mesh
                  name="Object_228"
                  
                  
                  geometry={nodes.Object_228.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder056_112"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_230"
                    
                    
                    geometry={nodes.Object_230.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus057_115" position={[-4.213, -2.306, -0.005]}>
                <mesh
                  name="Object_232"
                  
                  
                  geometry={nodes.Object_232.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder057_114"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_234"
                    
                    
                    geometry={nodes.Object_234.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus058_117" position={[2.301, -4.218, -0.005]}>
                <mesh
                  name="Object_236"
                  
                  
                  geometry={nodes.Object_236.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder058_116"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_238"
                    
                    
                    geometry={nodes.Object_238.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus059_119" position={[-2.301, 4.208, -0.005]}>
                <mesh
                  name="Object_240"
                  
                  
                  geometry={nodes.Object_240.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder059_118"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_242"
                    
                    
                    geometry={nodes.Object_242.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus060_121" position={[1.352, 4.601, -0.005]}>
                <mesh
                  name="Object_244"
                  
                  
                  geometry={nodes.Object_244.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder060_120"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_246"
                    
                    
                    geometry={nodes.Object_246.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus061_123" position={[-1.352, -4.611, -0.005]}>
                <mesh
                  name="Object_248"
                  
                  
                  geometry={nodes.Object_248.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder061_122"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_250"
                    
                    
                    geometry={nodes.Object_250.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus062_125" position={[4.606, -1.357, -0.005]}>
                <mesh
                  name="Object_252"
                  
                  
                  geometry={nodes.Object_252.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder062_124"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_254"
                    
                    
                    geometry={nodes.Object_254.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus063_127" position={[-4.606, 1.347, -0.005]}>
                <mesh
                  name="Object_256"
                  
                  
                  geometry={nodes.Object_256.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder063_126"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_258"
                    
                    
                    geometry={nodes.Object_258.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus064_129" position={[-0.015, -0.433, -4.8]}>
                <mesh
                  name="Object_260"
                  
                  
                  geometry={nodes.Object_260.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder064_128"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_262"
                    
                    
                    geometry={nodes.Object_262.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus065_131" position={[-0.015, 0.423, 4.762]}>
                <mesh
                  name="Object_264"
                  
                  
                  geometry={nodes.Object_264.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder065_130"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_266"
                    
                    
                    geometry={nodes.Object_266.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus066_133" position={[-0.015, -4.786, 0.409]}>
                <mesh
                  name="Object_268"
                  
                  
                  geometry={nodes.Object_268.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder066_132"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_270"
                    
                    
                    geometry={nodes.Object_270.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus067_135" position={[-0.015, 4.776, -0.447]}>
                <mesh
                  name="Object_272"
                  
                  
                  geometry={nodes.Object_272.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder067_134"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_274"
                    
                    
                    geometry={nodes.Object_274.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus068_137" position={[-0.015, 3.073, -3.702]}>
                <mesh
                  name="Object_276"
                  
                  
                  geometry={nodes.Object_276.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder068_136"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_278"
                    
                    
                    geometry={nodes.Object_278.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus069_139" position={[-0.015, -3.083, 3.664]}>
                <mesh
                  name="Object_280"
                  
                  
                  geometry={nodes.Object_280.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder069_138"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_282"
                    
                    
                    geometry={nodes.Object_282.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus070_141" position={[-0.015, -3.688, -3.097]}>
                <mesh
                  name="Object_284"
                  
                  
                  geometry={nodes.Object_284.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder070_140"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_286"
                    
                    
                    geometry={nodes.Object_286.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus071_143" position={[-0.015, 3.678, 3.059]}>
                <mesh
                  name="Object_288"
                  
                  
                  geometry={nodes.Object_288.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder071_142"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_290"
                    
                    
                    geometry={nodes.Object_290.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus072_145" position={[-0.015, 1.379, -4.615]}>
                <mesh
                  name="Object_292"
                  
                  
                  geometry={nodes.Object_292.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder072_144"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_294"
                    
                    
                    geometry={nodes.Object_294.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus073_147" position={[-0.015, -1.389, 4.577]}>
                <mesh
                  name="Object_296"
                  
                  
                  geometry={nodes.Object_296.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder073_146"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_298"
                    
                    
                    geometry={nodes.Object_298.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus074_149" position={[-0.015, -4.601, -1.404]}>
                <mesh
                  name="Object_300"
                  
                  
                  geometry={nodes.Object_300.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder074_148"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_302"
                    
                    
                    geometry={nodes.Object_302.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus075_151" position={[-0.015, 4.591, 1.365]}>
                <mesh
                  name="Object_304"
                  
                  
                  geometry={nodes.Object_304.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder075_150"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_306"
                    
                    
                    geometry={nodes.Object_306.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus076_153" position={[-0.015, 4.224, -2.29]}>
                <mesh
                  name="Object_308"
                  
                  
                  geometry={nodes.Object_308.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder076_152"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_310"
                    
                    
                    geometry={nodes.Object_310.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus077_155" position={[-0.015, -4.234, 2.252]}>
                <mesh
                  name="Object_312"
                  
                  
                  geometry={nodes.Object_312.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder077_154"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_314"
                    
                    
                    geometry={nodes.Object_314.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus078_157" position={[-0.015, -2.276, -4.248]}>
                <mesh
                  name="Object_316"
                  
                  
                  geometry={nodes.Object_316.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder078_156"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_318"
                    
                    
                    geometry={nodes.Object_318.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus079_159" position={[-0.015, 2.266, 4.21]}>
                <mesh
                  name="Object_320"
                  
                  
                  geometry={nodes.Object_320.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder079_158"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_322"
                    
                    
                    geometry={nodes.Object_322.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus080_161" position={[-0.015, 0.561, -4.786]}>
                <mesh
                  name="Object_324"
                  
                  
                  geometry={nodes.Object_324.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder080_160"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_326"
                    
                    
                    geometry={nodes.Object_326.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus081_163" position={[-0.015, -0.571, 4.747]}>
                <mesh
                  name="Object_328"
                  
                  
                  geometry={nodes.Object_328.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder081_162"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_330"
                    
                    
                    geometry={nodes.Object_330.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus082_165" position={[-0.015, -4.772, -0.585]}>
                <mesh
                  name="Object_332"
                  
                  
                  geometry={nodes.Object_332.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder082_164"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_334"
                    
                    
                    geometry={nodes.Object_334.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus083_167" position={[-0.015, 4.762, 0.547]}>
                <mesh
                  name="Object_336"
                  
                  
                  geometry={nodes.Object_336.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder083_166"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_338"
                    
                    
                    geometry={nodes.Object_338.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus084_169" position={[-0.015, 3.765, -2.99]}>
                <mesh
                  name="Object_340"
                  
                  
                  geometry={nodes.Object_340.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder084_168"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_342"
                    
                    
                    geometry={nodes.Object_342.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus085_171" position={[-0.015, -3.775, 2.951]}>
                <mesh
                  name="Object_344"
                  
                  
                  geometry={nodes.Object_344.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder085_170"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_346"
                    
                    
                    geometry={nodes.Object_346.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus086_173" position={[-0.015, -2.975, -3.789]}>
                <mesh
                  name="Object_348"
                  
                  
                  geometry={nodes.Object_348.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder086_172"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_350"
                    
                    
                    geometry={nodes.Object_350.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus087_175" position={[-0.015, 2.966, 3.751]}>
                <mesh
                  name="Object_352"
                  
                  
                  geometry={nodes.Object_352.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder087_174"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_354"
                    
                    
                    geometry={nodes.Object_354.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus088_177" position={[-0.015, 2.296, -4.232]}>
                <mesh
                  name="Object_356"
                  
                  
                  geometry={nodes.Object_356.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder088_176"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_358"
                    
                    
                    geometry={nodes.Object_358.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus089_179" position={[-0.015, -2.306, 4.194]}>
                <mesh
                  name="Object_360"
                  
                  
                  geometry={nodes.Object_360.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder089_178"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_362"
                    
                    
                    geometry={nodes.Object_362.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus090_181" position={[-0.015, -4.218, -2.32]}>
                <mesh
                  name="Object_364"
                  
                  
                  geometry={nodes.Object_364.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder090_180"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_366"
                    
                    
                    geometry={nodes.Object_366.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus091_183" position={[-0.015, 4.208, 2.282]}>
                <mesh
                  name="Object_368"
                  
                  
                  geometry={nodes.Object_368.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder091_182"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_370"
                    
                    
                    geometry={nodes.Object_370.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Torus092_185" position={[-0.015, 4.601, -1.371]}>
                <mesh
                  name="Object_372"
                  
                  
                  geometry={nodes.Object_372.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder092_184"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_374"
                    
                    
                    geometry={nodes.Object_374.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Torus093_187" position={[-0.015, -4.611, 1.333]}>
                <mesh
                  name="Object_376"
                  
                  
                  geometry={nodes.Object_376.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder093_186"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_378"
                    
                    
                    geometry={nodes.Object_378.geometry}
                    material={materials.material_2}
                  />
                </group>
              </group>
              <group name="Torus094_189" position={[-0.015, -1.357, -4.625]}>
                <mesh
                  name="Object_380"
                  
                  
                  geometry={nodes.Object_380.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder094_188"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_382"
                    
                    
                    geometry={nodes.Object_382.geometry}
                    material={materials.material_3}
                  />
                </group>
              </group>
              <group name="Torus095_191" position={[-0.015, 1.347, 4.587]}>
                <mesh
                  name="Object_384"
                  
                  
                  geometry={nodes.Object_384.geometry}
                  material={materials["Material.001"]}
                />
                <group
                  name="Cylinder095_190"
                  position={[0.002, -4.464, 0]}
                  rotation={[Math.PI / 2, 0.003, Math.PI / 2]}
                  scale={[0.014, 0.002, 0.014]}
                >
                  <mesh
                    name="Object_386"
                    
                    
                    geometry={nodes.Object_386.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
              <group name="Sphere_333" scale={5.274}>
                <mesh
                  name="Object_388"
                  
                  
                  geometry={nodes.Object_388.geometry}
                  material={materials["00000"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./assets/models/cosmic_speedways.glb");
